### PR TITLE
Pin google provider and terraform versions due to breaking changes

### PR DESCRIPTION
**Pull request by nkraemer-sysdig**
Pin version of the GCP provider due to breaking changes introduced in 5.0.0
Pin version of terraform used in cloudconnector module due to breaking changes in 1.6.0

### CODE REVIEW

**Comment by wideawakening** [comment]
also need to update examples.
pre-commit version validation is not working as expected. tried with couple of hacks but to no avail.

guess we can merge, but we should add a warning on the onboarding for the fixed TF version

**Review by wideawakening — APPROVED** [review]

**Comment by nkraemer-sysdig** [comment]
> also need to update examples.
Do the examples need to be updated? Don't they inherit the constraints from the modules?

> please followup to add a warning on the onboarding/doc for the fixed TF version < 1.6
Do you mean in the UI or the sysdig docs? (or both)?

Going to merge this as current installs are broken, will follow up with additional PRs to address these comments

**Review by haresh-suresh — APPROVED** [review]

**Comment by wideawakening** [comment]
version restrictions are per module, and examples don't seem to inherit it upwards 🤔 have not checked but maybe there is some way to avoid that maintenance. i already addressed that on the PR!

yeah, i would update requirements on this module everywhere it appears (onboarding and docs)

**Comment by nkraemer-sysdig** [comment]
Thanks @wideawakening, I missed that you already updated the other version files. I will take a pass of the docs and make sure to update them as needed, and yes I already released these changes =)

**Pull request merged**
