### PR TITLE
fix(Documentation): Update CIEM required APIs

### PR DESCRIPTION
**Pull request by gautam417**
This PR includes documenting all of the required APIs for CIEM

### CODE REVIEW

**Comment by aviad-chen-apolicy** [comment]
Shouldn't we add a new section in the readme file about CIEM? We will have specific CIEM APIs now, and it can save back and forth questions with customer on why is the API needed

**Comment by wideawakening** [comment]
Agree, APIs are listed per feature requirement.
Same with `Identity and access management API` not sure it belongs to Cloud Scanning, since that's image scanning. Maybe we could clarify that too.

**Comment by gautam417** [comment]
> Shouldn't we add a new section in the readme file about CIEM? We will have specific CIEM APIs now, and it can save back and forth questions with customer on why is the API needed

Great idea, I've added a new section dedicated for CIEM. @aviad-chen-apolicy Is it true that CIEM requires the same API's that Cloud Scanning does? (Since CIEM depends on Cloud Inventory APIs)

> > Agree with @aviad-chen-apolicy there; APIs are listed per feature requirement, so Recommendations API don't belong there. Same with Identity and access management API it makes more sense as CIEM
> > Also consider renaming
> > - Cloud Scanning > Image Cloud Scanning
> > - Cloud Benchmarks maybe Compliance?

@wideawakening Can you explain the reasoning for adding `Image`? I understood `Cloud Scanning` as scraping the cloud assets from a cloud account.  @aviad-chen-apolicy please correct me if I am wrong

I agree, we can rename Cloud Benchmarks > Compliance ✔️

**Comment by wideawakening** [comment]
> @wideawakening Can you explain the reasoning for adding `Image`? I understood `Cloud Scanning` as scraping the cloud assets from a cloud account.

this is legacy event-based image scanning, disabled by default

**Comment by gautam417** [comment]
@nkraemer-sysdig @haresh-suresh @cgeers I am closing this PR because it will be incorporated into our new GCP Onboarding Wizard initiatives

Please refer to the comments in this PR for the recommendations provided by @wideawakening and @aviad-chen-apolicy

**Pull request closed without merging**
